export enum PermissionType {
  ROLE_CREATE = "role-create",
  ROLE_VIEW = "role-view",
  ROLE_UPDATE = "role-update",
  ROLE_DELETE = "role-delete",
  PERMISSION_VIEW = "permission-view",
  POST_CREATE = "post-create",
  POST_VIEW = "post-view",
  POST_UPDATE = "post-update",
  POST_PUBLISH = "post-publish",
  POST_DELETE = "post-delete",
  COMMENT_CREATE = "comment-create",
  COMMENT_VIEW = "comment-view",
  COMMENT_UPDATE = "comment-update",
  COMMENT_DELETE = "comment-delete",
  USER_VIEW = "user-view",
  USER_UPDATE = "user-update",
  USER_DELETE = "user-delete",
}
